[[branch_types]]
name = "feature"
create = "feature/{BRANCH_NAME}"
from = "dev"
to = [{ name = "dev", strategy = "merge" }]

[[branch_types]]
name = "hotfix"
create = "hotfix/{BRANCH_NAME}"
from = "main"
to = [
  { name = "main", strategy = "merge" },
  { name = "dev", strategy = "merge" },
  { name = "feature/*", strategy = "merge" },
]
